name: GHA Templates, Examples, Context dump, etc.
run-name: GHA Templates, Examples, Context dump, etc.
# Run by ${{ github.actor }}
# on: [push]
on:
  push:
    branches:
      - blah
      # - main
      # - serverbooter
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub, Job, Steps, Runner, Strategy, and Matrix context
      # src: https://docs.github.com/en/actions/learn-github-actions/contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: |
          echo "GITHUB_CONTEXT"
          echo "$GITHUB_CONTEXT"
          echo "JOB_CONTEXT"
          echo "$JOB_CONTEXT"
          echo "STEPS_CONTEXT"
          echo "$STEPS_CONTEXT"
          echo "RUNNER_CONTEXT"
          echo "$RUNNER_CONTEXT"
          echo "STRATEGY_CONTEXT"
          echo "$STRATEGY_CONTEXT"
          echo "MATRIX_CONTEXT"
          echo "$MATRIX_CONTEXT"
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
